name: "Updated Releases"
on: [push]

jobs:
  releases:
    name: "Updated Releases"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Get Releases
        run: pip3 install beautifulsoup4 requests && python3 main.py
        shell: bash
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: Releases
      #     path: releases
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated Release Files
