name: "Update Releases"
on:
  schedule:
    - cron: "0/30 0-23 * * *"
jobs:
  releases:
    name: "Update Release Files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Get Github Releases
        run: pip3 install beautifulsoup4 requests && python3 automation/main.py
        shell: bash
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Releases
      #     path: releases
      - name: Upload and Commit Release Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated Release Files
